### ISSUE TITLE
Try Grunt or any other task runner.

### ISSUE THREAD

**Issue by ghost** [SOSCET/home#3]
There are an less file in "/css",
you may want to try Grunt,
and change your directory structure to following type: 
/
... /src
... ... /less
... ... /coffee
... /public
... ... /assets
... ... ... /stylesheets
... ... ... /scripts

**Comment by TsundereChen** [comment]
Good advice,
I will take this advice.

**Comment by ghost** [comment]
Please keep your commits clean, and correct your English or try Google Translate.
You may want to use your local language for commit messages.

**Comment by TsundereChen** [comment]
1. There are some mistakes in your messages, so... I really don't understand why you tell me to " Correct my English".
2. Next time, try to send Pull Request, or commit to this repo by yourself.

**Comment by ghost** [comment]
問題ありえません。
I dont want to contribute the repository since your codes are too "wet."

**Comment by ghost** [comment]
/public/assets/scripts
/public/assets/stylesheets
Why dont you use CDNs, did you include they into your git repo?

/public/assets/images
There are some images your site using, but in your less file,
    background-image: url("https://s3-ap-northeast-1.amazonaws.com/tsundere-aws/header_back.jpg");
why dont you put them into the same directory.

って
div.navbar-wrapper
div.header
必要ないなぁこの「div」、

「DRY」というもの知ってる？

**Comment by TsundereChen** [comment]
If you think my codes are too "wet",
1. Try not to view my codes
2. Contribute to this repo, and fix " those problems " by yourself

**Comment by ghost** [comment]
自分のことは自分でやろう

**Comment by ghost** [comment]
https://github.com/SOSCET/home/compare/6949fdd...d8d97c7

注意閱讀動線
小心選擇字體
對齊你的圖標
統一你的單位
代碼保持整潔
Code Style 保持一致
遵守 DRY 與 KISS 原則
使用前請配合手冊服用
三餐飯後及睡前，記得搭配溫開水
